### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by PhoenixBodrov** [otelo2/Obsidian-AI#1]
Need Help
I don't get it, there is no plugin in Obsidian. I don't have a lot of experience, how to install it? Can someone make a video? I really need this plug-in but i'm stuck on step one, i don't understand any instructions and don't even get there is the plugin itself..

Can someone give step by step instruction? What to download and so on? Or video guide? I might not be the only one person confused about all this..

![изображение](https://user-images.githubusercontent.com/100290554/222875450-9db73d3a-56e5-41d8-8f63-2ca54cce0010.png)

**Comment by PhoenixBodrov** [comment]
What does it mean "InstallGo"? and where to put this command after "Install Go"?
I don't understand "Build" section, what does it mean? Should i do it? Those are just commands, where do i paste them?

![изображение](https://user-images.githubusercontent.com/100290554/222875543-49d51225-bf0f-42bd-a1cd-f4c0b20d74c5.png)

**Comment by PhoenixBodrov** [comment]
I don;t understand "Build" section, what does it mean? Should i do it? Those are just commands, where do i paste them?

**Comment by antoniosolismz** [comment]
Thanks for your interest. In the following two days I'll update it with clear install instructions and a way better setup. I'll update you once that update is done

**Comment by antoniosolismz** [comment]
@PhoenixBodrov Readme has been updated with install instructions.
In short, you have to download the main.js and manifest from the releases tab, put them in a folder inside your vaults directory, enable it in obsidian, and input your openai api key
