### ISSUE TITLE
Followed the instructions, didn't appear in the plugins

### ISSUE THREAD

**Issue by MarekVeneny** [otelo2/Obsidian-AI#2]
Hey, I followed the instructions and got the two files you mentioned in the plugins/obsidian-ai folders but the plugin did not appear even after several restarts of obsidian.

**Comment by antoniosolismz** [comment]
@MarekVeneny 
Can you give me the full route to the files?
I probably forgot to add a step to the instructions

**Comment by MarekVeneny** [comment]
Sure, this is how it looks in my system: C:\Users\venen\Documents\Obsidian 2.0\plugins\obsidian-ai

**Comment by antoniosolismz** [comment]
Oh yeah that's my bad. 
It should be {your_vault_name}/.obsidian/plugins/obsidian-ai/{the three files here}
Let me know if that works
Thanks for bringing this up. I'll update the install instructions

**Comment by MarekVeneny** [comment]
It works now, thanks for the help!
