### ISSUE TITLE
Unfortunately still unable to run 😞

### ISSUE THREAD

**Issue by yarub123** [otelo2/Obsidian-AI#4]
I know how to install plugins both manually and through the community plugins community in Obsidian. 

Copied the files over into .obsidian and into the plugins folder and still this is what I'm getting:

It shows up normally:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/84487964/236371167-b7662f26-1839-4889-b614-499a554a4355.png">

and then when trying to turn it on: (it says failed 3 times because I pressed it multiple times so I can take the screenshot)
<img width="233" alt="image" src="https://user-images.githubusercontent.com/84487964/236371208-4c142253-37d3-4484-843b-4c4759514808.png">

**Comment by antoniosolismz** [comment]
Oh that's odd. Can you please send me the screenshot of doing the same thing but with the console open (ctrl + shift + i)? I can't reproduce it

**Comment by yarub123** [comment]
@otelo2 apologies for the late-ish response and for not including the console screenshots. Totally forgot to add those. But I think the issue seems to be somewhere in main.js. In the following screenshots they might look a little weird but I just left out portions that include my name and didn't want to put those online:
<img width="556" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/09abebe4-0352-4e18-937f-dfc9bcdfe75b">

<img width="265" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/73652378-41af-4218-a7d1-8ffdde297346">




Sorry if it looks a bit messey 😅 lol.

**Comment by antoniosolismz** [comment]
@yarub123 No worries, thanks for following up and for the trouble of adding the images.

I'm having trouble reproducing that error...
I doubt that this is the issue, but can you try adding the files again? Specially the main.js

The only way I managed to get the same error was by deleting "main.js" Maybe your antivirus deleted it or something?
![image](https://github.com/otelo2/Obsidian-AI/assets/10353204/f61d84d7-919a-4ce9-9ed8-379d330035c4)

For reference, the first error is what I would expect for an issue with the code. The second error is when I deleted main.js

**Comment by yarub123** [comment]
@otelo2 Thanks yet again for the response. And no no trouble at all 😅, in fact thank you for getting in touch. 

I couldn't solve it, so I tried also changing the file name from the main repo which was "main.ts" to "main.js"

Anyways still the same issue, now getting this error: (starts off with 
<img width="911" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/b2fa2964-103b-4e25-823c-6613878d7757">

And nope, have no antivirus or nothin on here lol. Also I'm on MacOS I forgot to mention (I also turned off firewall and created a local vault to test the issue with no other plugins.

So I messed around and downloaded your "main.ts" (I think that's typescript, but it's also a Transport Stream file type)

After downloading your "main.ts" and importing I get the same error of "no such file or directory," here's the newest screenshot:
<img width="907" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/a2ceb6ec-08b6-4f16-a725-105b92494483">

After renaming to "main.js" I get this error:
<img width="907" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/4fe6539a-a9ca-4326-b357-2910dd7828e1">

Edit: here is where "Cannot use import statement outside a module" takes me after clicking "VM224 plugin:copy-ai:1:45" (I only screenshotted first line since it's an import issue I think 🤷)
<img width="1039" alt="image" src="https://github.com/otelo2/Obsidian-AI/assets/84487964/a3a0b8fd-cc1f-40fa-b0dc-686e94405a1b">

**Comment by antoniosolismz** [comment]
@yarub123 Oh real quick question, are you getting the main.js file from the [Releases section](https://github.com/otelo2/Obsidian-AI/releases/tag/0.1.7)?

**Comment by yarub123** [comment]
@otelo2 I think the fix is somewhere in here but I'm too dumb to figure it out. https://stackoverflow.com/questions/58211880/uncaught-syntaxerror-cannot-use-import-statement-outside-a-module-when-import


Oops nvm disregard all that. bahahahahah fuck. It was in the releases section I was downloading the fucking source files from main repo 😂😂😂. 🤦‍♂️🤦‍♂️🤦‍♂️ Im done bye. K it works ♥️

**Comment by antoniosolismz** [comment]
Yaaaaay I'm so glad it works hahaha I would have been lost if it wasn't that
Thanks for all your patience 😆

**Comment by yarub123** [comment]
@otelo2 LOOL I'm done with the internet. Yes you're right. I'm glad I mentioned the ".ts" file 🙃 😂😂
